backend/config/routes.rb
Spree::Core::Engine.routes.draw do
  get '/admin', :to => 'admin/orders#index', :as => :admin

  namespace :admin do
    get '/search/users', :to => "search#users", :as => :search_users

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
    end

    resources :adjustments
    resources :zones
    resources :banners do
      member do
        post :dismiss
      end
    end
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
        get :stock
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
    end

    get '/variants/search', :to => "variants#search", :as => :search_variants

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', :to => "option_values#destroy", :as => :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', :to => "product_properties#destroy", :as => :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :image_settings

    resources :orders, :except => [:show] do
      member do
        put :fire
        get :fire
        post :resend
        get :open_adjustments
        get :close_adjustments
      end

      resource :customer, :controller => "orders/customer_details"

      resources :adjustments do
        member do
          get :toggle_state
        end
      end
      resources :line_items
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
      collection do
      	post :update_positions
      end
      member do
        get :get_children
      end
      resources :taxons
    end

    resources :taxons, :only => [] do
      collection do
        get :search
      end
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :shipping_methods
    resources :shipping_categories
    resources :stock_transfers, :only => [:index, :show, :new, :create]
    resources :stock_locations do
      resources :stock_movements, :except => [:edit, :update, :destroy]
      collection do
        post :transfer_stock
      end
    end

    resources :stock_movements
    resources :stock_items, :only => [:create, :update, :destroy]
    resources :tax_rates
    resource  :tax_settings

    resources :trackers
    resources :payment_methods
    resource :mail_method, :only => [:edit, :update] do
      post :testmail, :on => :collection
    end
  end
end

backend/app/controllers/spree/admin/option_types_controller.rb
module Spree
  module Admin
    class OptionTypesController < ResourceController
      before_filter :setup_new_option_value, :only => [:edit]

      def update_values_positions
        params[:positions].each do |id, index|
          OptionValue.where(:id => id).update_all(:position => index)
        end

        respond_to do |format|
          format.html { redirect_to admin_product_variants_url(params[:product_id]) }
          format.js  { render :text => 'Ok' }
        end
      end

      protected

        def location_after_save
          if @option_type.created_at == @option_type.updated_at
            edit_admin_option_type_url(@option_type)
          else
            admin_option_types_url
          end
        end


      private
        def load_product
          @product = Product.find_by_param!(params[:product_id])
        end

        def setup_new_option_value
          @option_type.option_values.build if @option_type.option_values.empty?
        end

        def set_available_option_types
          @available_option_types = if @product.option_type_ids.any?
            OptionType.where('id NOT IN (?)', @product.option_type_ids)
          else
            OptionType.all
          end
        end
    end
  end
end

backend/app/views/spree/admin/option_types/_form.html.erb
<div data-hook="admin_option_type_form_fields" class="align-center row">
  <div class="alpha eight columns">
    <%= f.field_container :name do %>
      <%= f.label :name, Spree.t(:name) %> <span class="required">*</span><br />
      <%= f.text_field :name, :class => "fullwidth" %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>

  <div class="omega eight columns">
    <%= f.field_container :presentation do %>
      <%= f.label :presentation, Spree.t(:presentation) %> <span class="required">*</span><br />
      <%= f.text_field :presentation, :class => "fullwidth" %>
      <%= f.error_message_on :presentation %>
    <% end %>
  </div>
</div>

backend/app/views/spree/admin/option_types/_option_value_fields.html.erb
<tr class="option_value fields" id="spree_<%= dom_id(f.object) %>"  data-hook="option_value" class="<%= cycle('odd', 'even')%>">
  <td class="no-border">
    <span class="handle"></span>
    <%= f.hidden_field :id %>
  </td>
  <td class="name"><%= f.text_field :name %></td>
  <td class="presentation"><%= f.text_field :presentation %></td>
  <td class="actions"><%= link_to_remove_fields Spree.t(:remove), f, :no_text => true %></td>
</tr>

backend/app/views/spree/admin/option_types/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:editing_option_type) %> <span class="green">"<%= @option_type.name %>"</span>
<% end %>

<% content_for :page_actions do %>
  <li>
    <span id="new_add_option_value" data-hook>
      <%= link_to_add_fields Spree.t(:add_option_value), "tbody#option_values", :class => 'button icon-plus' %>
    </span>      
  </li>
  <li>
    <%= button_link_to Spree.t(:back_to_option_types_list), spree.admin_option_types_path, :icon => 'icon-arrow-left' %>
  </li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @option_type } %>

<%= form_for [:admin, @option_type] do |f| %>
  <fieldset>
    <legend align="center"><%= Spree.t(:option_values) %></legend>
    
    <%= render :partial => 'form', :locals => { :f => f } %>

    <table class="index sortable" data-hook data-sortable-link="<%= update_values_positions_admin_option_types_url %>">
      <thead data-hook="option_header">
        <tr>
          <th colspan="2"><%= Spree.t(:name) %></th>
          <th><%= Spree.t(:display) %></th>
          <th class="actions"></th>
        </tr>
      </thead>
      <tbody id="option_values">
        <% if @option_type.option_values.empty? %>
          <tr id="none" data-hook="option_none" class="<%= cycle('odd', 'even')%>">
            <td colspan="2"><%= Spree.t(:none) %></td>
            <td class="actions"></td>
          </tr>
        <% else %>
          <%= f.fields_for :option_values do |option_value_form| %>
            <%= render :partial => 'option_value_fields', :locals => { :f => option_value_form } %>
          <% end %>
        <% end %>
      </tbody>
    </table>

    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

backend/app/views/spree/admin/option_types/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:option_types) %>
<% end %>

<% content_for :page_actions do %>
  <li id="new_ot_link">
    <%= button_link_to Spree.t(:new_option_type), new_admin_option_type_url, { :remote => true, :icon => 'icon-plus', :id => 'new_option_type_link' } %>
  </li>
<% end %>

<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<div id="new_option_type"></div>

<% if @option_types.any? %>
<table class="index sortable" id="listing_option_types" data-hook data-sortable-link="<%= update_positions_admin_option_types_url %>">
  <colgroup>
    <col style="width: 10%">
    <col style="width: 35%">
    <col style="width: 40%">
    <col style="width: 15%">
  </colgroup>
  <thead>
    <tr data-hook="option_header">
      <th class="no-border"></th>
      <th><%= Spree.t(:name) %></th>
      <th><%= Spree.t(:presentation) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @option_types.each do |option_type| %>
      <tr class="spree_option_type <%= cycle('odd', 'even')%>" id="<%= spree_dom_id option_type %>" data-hook="option_row">
        <td class="no-border"><span class="handle"></span></td>
        <td class="align-center"><%= option_type.name %></td>
        <td class="align-center presentation"><%= option_type.presentation %></td>
        <td class="actions">
          <%= link_to_edit(option_type, :class => 'admin_edit_option_type', :no_text => true) %>
          <%= link_to_delete(option_type, :no_text => true) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/option_type')) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_option_type_path %>!
  </div>
<% end %>

backend/app/views/spree/admin/option_types/new.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @option_type } %>

<%= form_for [:admin, @option_type] do |f| %>
  <fieldset>
    <legend align="center"><%= Spree.t(:new_option_type) %></legend>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

backend/app/views/spree/admin/option_types/new.js.erb
$("#new_option_type").html('<%= escape_javascript(render :template => "spree/admin/option_types/new", :formats => [:html], :handlers => [:erb]) %>');
$("#new_option_type_link").parent().hide();