backend/config/routes.rb
Spree::Core::Engine.routes.draw do
  get '/admin', :to => 'admin/orders#index', :as => :admin

  namespace :admin do
    get '/search/users', :to => "search#users", :as => :search_users

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
    end

    resources :adjustments
    resources :zones
    resources :banners do
      member do
        post :dismiss
      end
    end
    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
        get :stock
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
    end

    get '/variants/search', :to => "variants#search", :as => :search_variants

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', :to => "option_values#destroy", :as => :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', :to => "product_properties#destroy", :as => :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resource :image_settings

    resources :orders, :except => [:show] do
      member do
        put :fire
        get :fire
        post :resend
        get :open_adjustments
        get :close_adjustments
      end

      resource :customer, :controller => "orders/customer_details"

      resources :adjustments do
        member do
          get :toggle_state
        end
      end
      resources :line_items
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end
      end
    end

    resource :general_settings do
      collection do
        post :dismiss_alert
      end
    end

    resources :taxonomies do
      collection do
      	post :update_positions
      end
      member do
        get :get_children
      end
      resources :taxons
    end

    resources :taxons, :only => [] do
      collection do
        get :search
      end
    end

    resources :reports, :only => [:index, :show] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :shipping_methods
    resources :shipping_categories
    resources :stock_transfers, :only => [:index, :show, :new, :create]
    resources :stock_locations do
      resources :stock_movements, :except => [:edit, :update, :destroy]
      collection do
        post :transfer_stock
      end
    end

    resources :stock_movements
    resources :stock_items, :only => [:create, :update, :destroy]
    resources :tax_rates
    resource  :tax_settings

    resources :trackers
    resources :payment_methods
    resource :mail_method, :only => [:edit, :update] do
      post :testmail, :on => :collection
    end
  end
end

backend/app/controllers/spree/admin/product_properties_controller.rb
module Spree
  module Admin
    class ProductPropertiesController < ResourceController
      belongs_to 'spree/product', :find_by => :permalink
      before_filter :find_properties
      before_filter :setup_property, :only => [:index]

      private
        def find_properties
          @properties = Spree::Property.pluck(:name)
        end

        def setup_property
          @product.product_properties.build
        end
    end
  end
end

backend/app/views/spree/admin/product_properties/_product_property_fields.html.erb
<tr class="product_property fields" id="spree_<%= dom_id(f.object) %>" data-hook="product_property">
  <td class="no-border">
    <span class="handle"></span>
    <%= f.hidden_field :id %>
  </td>
  <td class='property_name'>
    <%= f.text_field :property_name, :class => 'autocomplete' %>
  </td>
  <td class='value'>
    <%= f.text_field :value %>
  </td>
  <td class="actions">
    <% if f.object.persisted? %>
      <%= link_to_delete f.object, :no_text => true %>
    <% end %>
  </td>
</tr>

backend/app/views/spree/admin/product_properties/index.html.erb
<%= render 'spree/admin/shared/product_sub_menu' %>
<%= render 'spree/admin/shared/product_tabs', :current => 'Product Properties' %>
<%= render 'spree/shared/error_messages', :target => @product %>

<% content_for :page_actions do %>
  <ul class="tollbar inline-menu">
    <li>
      <%= link_to_add_fields Spree.t(:add_product_properties), 'tbody#product_properties', :class => 'icon-plus button' %>
    </li>
    <li>
      <span id="new_ptype_link">
        <%= link_to Spree.t(:select_from_prototype), available_admin_prototypes_url, :remote => true, 'data-update' => 'prototypes', :class => 'button icon-copy' %>
      </span>
    </li>
  </ul>
<% end %>

<%= form_for @product, :url => admin_product_url(@product), :method => :put do |f| %>
  <fieldset class="no-border-top">
    <div class="add_product_properties" data-hook="add_product_properties"></div>

    <div id="prototypes" data-hook></div>
    <%= image_tag 'select2-spinner.gif', :plugin => 'spree', :style => 'display:none;', :id => 'busy_indicator' %>

    <table class="index sortable" data-hook data-sortable-link="<%= update_positions_admin_product_product_properties_url %>">
      <thead>
        <tr data-hook="product_properties_header">
          <th colspan="2"><%= Spree.t(:property) %></th>
          <th><%= Spree.t(:value) %></th>
          <th class="actions"></th>
        </tr>
      </thead>
      <tbody id="product_properties" data-hook>
        <%= f.fields_for :product_properties do |pp_form| %>
          <%= render 'product_property_fields', :f => pp_form %>
        <% end %>
      </tbody>
    </table>

    <%= render 'spree/admin/shared/edit_resource_links' %>

    <%= hidden_field_tag 'clear_product_properties', 'true' %>
  </fieldset>
<% end %>

<%= javascript_tag do -%>
  var properties = <%= raw(@properties.to_json) %>;
  $('#product_properties').on('keydown', 'input.autocomplete', function() {
    already_auto_completed = $(this).is('ac_input');
    if (!already_auto_completed) {
      $(this).autocomplete({source: properties});
      $(this).focus();
    }
  });
<% end -%>